name = "german-quiz"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "german_words"
database_id = "db382da6-3f5d-457a-8feb-526069eef165"
